### ISSUE TITLE
Composite glyphs must be initialized first.

### ISSUE THREAD

**Issue by create3000** [nodebox/opentype.js#157] opened 2015-08-30 07:25 UTC
In order to get composite glyphs to work, I found out that I have to 'initialize' the affected normal glyphs first:
Before I can use any composite glyph I found this workaround, than everything is fine:

		      // Workaround to initialize composite glyphs.
		      for (var i = 0; i < this .font .numGlyphs; ++ i)
					this .font .glyphs .get (i) .getPath (0, 0, 1);

I this due to the fact, that the glyphs are cached maybe?

**Comment by possan** [comment] 2015-09-09 10:46
Thank you! this solved my problem with composite glyphs!

**Comment by possan** [comment] 2015-09-09 10:47
For further debugging, just use http://nodebox.github.io/opentype.js/glyph-inspector.html load a font, try to write some swedish umlauts (åäöÅÄÖ) and they will display as (aaoAAO)

**Comment by kennethmac2000** [comment] 2016-07-04 09:58
Anyone know what needs to change in the code to make this happen automatically when a glyph is instantiated?

**Comment by kennethmac2000** [comment] 2016-07-04 10:01
It's also not clear to me that this issue only affects composite glyphs.

At least, I have glyphs (from a WOFF font) for which the property "isComposite" is not set, and I still have this issue of having to make 'fake' getPath() calls to initialize the glyphs.

**Comment by fdb** [comment] 2016-07-08 20:48
The composite glyphs need to be "kicked" into action through getPath(). The reason is that some fonts have an enormous amount of glyphs  (e.g. Chinese fonts) which can make the memory usage of OpenType.js blow up (this is problematic on embedded systems and servers).

The good news is that we can solve this. We just need to be a bit more careful when loading getPath() on composite glyphs that getPath() for the composites is also called.

@kennethmac2000 the WOFF issue is weird. Can you send me an example font + a bit of usage code so I can debug this?

**Comment by fdb** [comment] 2016-07-08 21:07
For composite glyphs I can no longer reproduce this. 

Here's the test code I use to draw a path:

```
opentype.load(FONT_URL, function(err, font) {
  console.assert(!err, err);
  var path = font.getPath('Öpéñtÿpè', 0, 200, 100);
  path.draw(ctx);
});
```

which shows all diacritics correctly:

![screenshot 2016-07-08 at 23 07 10](https://cloud.githubusercontent.com/assets/8477/16701559/ca115c80-4560-11e6-9104-9dd030997cb6.png)


See https://jsfiddle.net/zv7an0yx/ for a demo.

**Comment by kennethmac2000** [comment] 2016-07-11 15:51
I have a glyph (eg, "1") from this Google font: open-sans-v13-latin_latin-ext-600.woff

If I try to get glyph.yMax *before* calling glyph.getPath(), the value of glyph.yMax is undefined. If I call glyph.getPath() first, glyph.yMax then has a value. It's that simple. :)

**Comment by fdb** [comment] 2016-07-12 13:16
@kennethmac2000  OK so it's accessing yMax that's the problem, not getPath(). Thanks for clearing this up. I'll take a look.

**Comment by kennethmac2000** [comment] 2016-07-12 14:11
Yeah, there's no problem with getPath() per se, but, as per the comments above, getPath() seems to need to be called to 'kick' the glyphs into action.

**Comment by fdb** [comment] 2016-07-12 19:56
I've just pushed a fix so that metrics information is kept behind a JavaScript property that forces the path to load first. This should fix the issues with composite paths (although it's not just composite paths).

**Closed** 2016-07-12 19:55 UTC

**Comment by fpirsch** [comment] 2016-07-12 21:18
Beware that Object.defineProperty has some performance impact.

**Comment by kennethmac2000** [comment] 2016-07-12 21:56
Thanks!
