### ISSUE TITLE
Tree-shaking ready

### ISSUE THREAD

**Issue by kononenko-a-m** [nodebox/opentype.js#260] opened 2017-03-10 22:46 UTC
Hello, I try to make a library based on opentype, but also I want to reduce size build size, for example, if I gonna use it only for WOFF, then no code for TTF, SVG parsing needed, and it can be removed from target build (which is very desirable) using tree-shaking approach. Is there any chance that you would deliver this? Or maybe I just can prepare a PR which would introducing support for tree-shaking?

**Comment by Jolg42** [comment] 2017-03-29 12:24
Hi @kononenko-a-m 
So feel free to prepare a PR, just keep in mind that OpenType.js needs to run in the browser and Node.js ;) (Node.js as a package and in the browser with a browserify build).

**Comment by axkibe** [comment] 2017-05-04 20:48
I suppose this is in a way a duplicate of #247 
since all "treeshaking tools" I saw require an ES6 style export/import scheme.

**Comment by fdb** [comment] 2017-05-05 07:49
I have absolute no issue with this. Moving to the ES6 style export / import scheme would work for me. @kononenko-a-m if you want to work on this, feel free! I would prefer two pull requests:

- one to move to ES6 modules
- one to support tree shaking

**Comment by Jolg42** [comment] 2018-04-01 04:07
I guess it's already done as we now use Rollup.js

**Closed by Jolg42** 2018-04-01 04:07 UTC
