### ISSUE TITLE
Qustion: - What is the proper way to get measurements of an SVG Path

### ISSUE THREAD

**Issue by villanus** [nodebox/opentype.js#186] opened 2016-05-05 16:56 UTC
I have loaded a ttf font, and created a path using the path.toSvg method.

now I am trying to figure out how to measure the size of the path using either Jquery of vanilla javascript.   When I load the path into an empty svg, I am not able to get the height or width. 

What is the proper way to do this?

After 3 hours, I am still confused :8ball:

**Comment by Silverwolf90** [comment] 2016-05-06 15:38
You could give this a shot?

https://github.com/icons8/svg-path-bounding-box

**Comment by villanus** [comment] 2016-05-06 16:26
i am trying to do this in the browser not node

**Comment by fdb** [comment] 2016-05-10 10:17
Closing, as this is a duplicate of #124.

**Closed by fdb** 2016-05-10 10:17 UTC
