### ISSUE TITLE
glyphs need to be sorted before the font is generated, otherwise it gets corrupted

### ISSUE THREAD

**Issue by louisremi** [nodebox/opentype.js#75] opened 2014-11-06 18:57 UTC
When trying to generate a font, the glyphs need to be sorted, using a simple font.glyphs.sort() before converting it to a buffer. Otherwise the font gets corrupted.

(Sorry for this incomplete bug report, I've got to file it real quick before leaving the office, will try to produce reduced test-case tomorrow)

**Comment by fdb** [comment] 2015-01-17 15:41
Closing this for now, can't reproduce.

**Closed** 2015-01-17 15:40 UTC
